<?php
$PAYMENTDATETIME = $_POST['PAYMENTDATETIME'];
$PURCHASECURRENCY = $_POST['PURCHASECURRENCY'];
$PAYMENTCHANNEL = $_POST['PAYMENTCHANNEL'];
$AMOUNT = $_POST['AMOUNT'];
$PAYMENTCODE = $_POST['PAYMENTCODE'];
$MCN = $_POST['MCN'];
$WORDS = $_POST['WORDS'];
$RESULTMSG = $_POST['RESULTMSG'];
$VERIFYID = $_POST['VERIFYID'];
$TRANSIDMERCHANT = $_POST['TRANSIDMERCHANT'];
$BANK = $_POST['BANK'];
$STATUSTYPE = $_POST['STATUSTYPE'];
$APPROVALCODE = $POST['APPROVALCODE'];
$EDUSTATUS = $POST['EDUSTATUS'];
$THREEDSECURESTATUS = $POST['THREEDSECURESTATUS'];
$VERIFYSCORE = $POST['VERIFYSCORE'];
$CURRENCY = $POST['CURRENCY'];
$RESPONSECODE = $_POST['RESPONSECODE'];
$CHNAME = $POST['CHNAME'];
$BRAND = $POST['BRAND'];
$VERIFYSTATUS = $POST['VERIFYSTATUS'];
$SESSIONID = $_POST['SESSIONID'];
$LIABILITY = $_POST['LIABILITY'];
$WORDS_GENERATED = sha1 ($AMOUNT."10896632"."V5l5u8s5t2R9".$TRANSIDMERCHANT); 

if ( $WORDS == $WORDS_GENERATED )
{
echo 'CONTINUE';
if ($RESULTMSG == 'SUCCESS')
{
 // UPDATE DATABASE SUKSES
}
else
{
 // UPDATE DATABASE SUKSES
}
}
else
{
echo 'STOP - WORDS NOT MATCH';
}
?>